# Reproducible report ----------------------------------------------------------

# The generated-code panel already reconstructs a session as R. A report is
# the same material arranged for someone to read: the model, the code that
# produced it, the diagnostics that were run, and the readings, in one
# document that runs from top to bottom.
#
# It is written out as Quarto source rather than rendered here. Rendering would
# need a Quarto or pandoc installation, which is exactly the kind of dependency
# the equations work has just removed; and a source document is more useful
# anyway, because it can be edited before it is rendered.

ctgui_report_fence <- function(...) {
  c("```{r}", ..., "```")
}

ctgui_report_heading <- function(text, level = 2L) {
  c("", paste(strrep("#", level), text), "")
}

ctgui_report_prose <- function(...) {
  lines <- unlist(list(...), use.names = FALSE)
  if (!length(lines)) return(character())
  c("", lines, "")
}

# Code the GUI generated arrives as one string per action; a document needs it
# split back into lines so the fence renders.
ctgui_report_code_lines <- function(code) {
  if (is.null(code) || !length(code)) return(character())
  unlist(strsplit(paste(code, collapse = "\n"), "\n", fixed = TRUE), use.names = FALSE)
}

ctgui_report_front_matter <- function(title, generated = Sys.time()) {
  c(
    "---",
    paste0("title: \"", gsub("\"", "'", title), "\""),
    paste0("date: \"", format(generated, "%Y-%m-%d"), "\""),
    "format: html",
    "execute:",
    "  warning: true",
    "---"
  )
}

ctgui_report_readings <- function(notes) {
  if (!length(notes)) return(character())
  lines <- vapply(notes, function(note) {
    prefix <- if (identical(note$kind, "caution")) "**Worth checking.** " else ""
    paste0("- ", prefix, note$text)
  }, character(1L))
  c(
    ctgui_report_heading("Reading"),
    ctgui_report_prose(
      "These follow from the fitted drift matrix at its point estimates.",
      "The uncertainty around them is in the summary above."
    ),
    lines
  )
}

ctgui_report_warnings <- function(warnings, guidance = ctgui_warning_guidance(warnings)) {
  if (!length(warnings) || identical(trimws(paste(warnings, collapse = "")), "") ||
      identical(trimws(paste(warnings, collapse = "")), "No warnings.")) {
    return(character())
  }
  lines <- c(
    ctgui_report_heading("Warnings from the fit"),
    "```",
    ctgui_report_code_lines(warnings),
    "```"
  )
  for (entry in guidance) {
    lines <- c(lines, ctgui_report_prose(paste0("**", entry$title, ".** ", entry$text)))
  }
  lines
}

#' Build a reproducible Quarto report of the current analysis
#'
#' @param spec The `ctsemgui_spec` being reported.
#' @param source Data source description from `ctgui_output_data_source()`.
#' @param snippets Named list of generated code for actions that were run.
#' @param notes Interpretation notes from `ctgui_interpret_fit()`.
#' @param warnings Character vector of warnings the fit produced.
#' @param latex Model equations as LaTeX, if available.
#' @param has_fit Whether a fit exists to report on.
#' @param title Report title.
#' @return A character vector of Quarto source lines.
#' @keywords internal
ctgui_report_document <- function(spec, source = ctgui_output_data_source(),
    snippets = list(), notes = list(), warnings = character(), latex = NULL,
    has_fit = FALSE, title = "Continuous-time model report",
    generated = Sys.time()) {
  ctgui_check_spec(spec)

  lines <- ctgui_report_front_matter(title, generated)

  lines <- c(lines, ctgui_report_prose(paste(
    "Generated by ctsemGUI. Every result below is produced by the code in this",
    "document, so running it reproduces the analysis rather than describing it."
  )))

  lines <- c(lines,
    ctgui_report_heading("Data and model"),
    ctgui_report_fence(ctgui_report_code_lines(ctgui_output_base_code(spec, source)))
  )

  if (!is.null(latex) && length(latex) == 1L && nzchar(latex)) {
    view <- ctgui_equation_view(latex)
    if (identical(view$status, "rows")) {
      lines <- c(lines, ctgui_report_heading("Equations", 3L))
      for (block in view$blocks) {
        if (nzchar(block$label)) lines <- c(lines, ctgui_report_prose(paste0("*", block$label, "*")))
        lines <- c(lines, "$$", block$tex, "$$")
      }
    }
  }

  if (!length(snippets)) {
    lines <- c(lines, ctgui_report_prose(paste(
      "No fit or diagnostics have been run yet, so this report covers the model",
      "specification only."
    )))
    return(lines)
  }

  # Actions appear in the order they belong in a write-up rather than the order
  # they happened to be clicked, so the document reads as an analysis.
  order <- c("fit", "uncertainty", "summary", "summary_matrices", "generate_from_fit",
    "cov_check", "postpred", "residual_acf", "kalman", "dynamics", "tipred",
    "model_pars", "fit_comparison", "raw_plot")
  titles <- c(
    fit = "Fitting", uncertainty = "Uncertainty", summary = "Fit summary",
    summary_matrices = "Summary matrices", generate_from_fit = "Data generated from the fit",
    cov_check = "Covariance check", postpred = "Posterior predictive checks",
    residual_acf = "Residual autocorrelation", kalman = "Predictions",
    dynamics = "Dynamics over time", tipred = "Time-independent predictor effects",
    model_pars = "Model parameters", fit_comparison = "Fit comparison",
    raw_plot = "Data visualisation"
  )
  present <- c(intersect(order, names(snippets)), setdiff(names(snippets), order))

  for (action in present) {
    lines <- c(lines,
      ctgui_report_heading(titles[[action]] %||% action),
      ctgui_report_fence(ctgui_report_code_lines(snippets[[action]]))
    )
  }

  lines <- c(lines, ctgui_report_warnings(warnings))
  if (isTRUE(has_fit)) lines <- c(lines, ctgui_report_readings(notes))

  lines <- c(lines, ctgui_report_prose(paste(
    "Report generated", format(generated, "%Y-%m-%d %H:%M"), "by ctsemGUI",
    paste0("with ctsem ", ctgui_ctsem_capabilities()$version, ".")
  )))
  lines
}
